#ifndef HL7PARSER_SEG_OBX_H
#define HL7PARSER_SEG_OBX_H

/**
* \file seg_obx.h
*
* Observation segment (OBX) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2017 Juan Jose Comellas <juanjo@comellas.org>
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the hl7segdef.py script on Tue Nov 14 11:09:38 2017
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------
   Function prototypes
   ------------------------------------------------------------------------ */

/**
* Get the set_id (OBX.1) field.
*/
HL7_EXPORT int hl7_obx_set_id( HL7_Segment *segment );
/**
* Set the set_id (OBX.1) field.
*/
HL7_EXPORT int hl7_obx_set_set_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the set_id (OBX.1) field as an integer.
*/
HL7_EXPORT int hl7_obx_set_set_id_int( HL7_Segment *segment, const int value );
/**
* Get the value_type (OBX.2.1) component.
*/
HL7_EXPORT HL7_Element *hl7_obx_value_type( HL7_Segment *segment );
/**
* Set the value_type (OBX.2.1) component.
*/
HL7_EXPORT int hl7_obx_set_value_type( HL7_Segment *segment, HL7_Element *element );
/**
* Set the value_type (OBX.2.1) component as a string.
*/
HL7_EXPORT int hl7_obx_set_value_type_str( HL7_Segment *segment, const char *value );
/**
* Get the observation_identifier (OBX.3.1) component.
*/
HL7_EXPORT HL7_Element *hl7_obx_observation_identifier( HL7_Segment *segment );
/**
* Set the observation_identifier (OBX.3.1) component.
*/
HL7_EXPORT int hl7_obx_set_observation_identifier( HL7_Segment *segment, HL7_Element *element );
/**
* Set the observation_identifier (OBX.3.1) component as a string.
*/
HL7_EXPORT int hl7_obx_set_observation_identifier_str( HL7_Segment *segment, const char *value );
/**
* Get the observation_identifier_id (OBX.3.1.1) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_obx_observation_identifier_id( HL7_Segment *segment );
/**
* Set the observation_identifier_id (OBX.3.1.1) subcomponent.
*/
HL7_EXPORT int hl7_obx_set_observation_identifier_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the observation_identifier_id (OBX.3.1.1) subcomponent as a string.
*/
HL7_EXPORT int hl7_obx_set_observation_identifier_id_str( HL7_Segment *segment, const char *value );
/**
* Get the observation_identifier_text (OBX.3.1.2) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_obx_observation_identifier_text( HL7_Segment *segment );
/**
* Set the observation_identifier_text (OBX.3.1.2) subcomponent.
*/
HL7_EXPORT int hl7_obx_set_observation_identifier_text( HL7_Segment *segment, HL7_Element *element );
/**
* Set the observation_identifier_text (OBX.3.1.2) subcomponent as a string.
*/
HL7_EXPORT int hl7_obx_set_observation_identifier_text_str( HL7_Segment *segment, const char *value );
/**
* Get the observation_identifier_coding_system (OBX.3.1.3) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_obx_observation_identifier_coding_system( HL7_Segment *segment );
/**
* Set the observation_identifier_coding_system (OBX.3.1.3) subcomponent.
*/
HL7_EXPORT int hl7_obx_set_observation_identifier_coding_system( HL7_Segment *segment, HL7_Element *element );
/**
* Set the observation_identifier_coding_system (OBX.3.1.3) subcomponent as a string.
*/
HL7_EXPORT int hl7_obx_set_observation_identifier_coding_system_str( HL7_Segment *segment, const char *value );
/**
* Get the observation_sub_id (OBX.4) field.
*/
HL7_EXPORT HL7_Element *hl7_obx_observation_sub_id( HL7_Segment *segment );
/**
* Set the observation_sub_id (OBX.4) field.
*/
HL7_EXPORT int hl7_obx_set_observation_sub_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the observation_sub_id (OBX.4) field as a string.
*/
HL7_EXPORT int hl7_obx_set_observation_sub_id_str( HL7_Segment *segment, const char *value );
/**
* Get the observation_value_text (OBX.5) field.
*/
HL7_EXPORT HL7_Element *hl7_obx_observation_value_text( HL7_Segment *segment );
/**
* Set the observation_value_text (OBX.5) field.
*/
HL7_EXPORT int hl7_obx_set_observation_value_text( HL7_Segment *segment, HL7_Element *element );
/**
* Set the observation_value_text (OBX.5) field as a string.
*/
HL7_EXPORT int hl7_obx_set_observation_value_text_str( HL7_Segment *segment, const char *value );
/**
* Get the observation_value (OBX.5.1) component.
*/
HL7_EXPORT HL7_Element *hl7_obx_observation_value( HL7_Segment *segment );
/**
* Set the observation_value (OBX.5.1) component.
*/
HL7_EXPORT int hl7_obx_set_observation_value( HL7_Segment *segment, HL7_Element *element );
/**
* Set the observation_value (OBX.5.1) component as a string.
*/
HL7_EXPORT int hl7_obx_set_observation_value_str( HL7_Segment *segment, const char *value );
/**
* Get the units_id (OBX.6.1.1) component.
*/
HL7_EXPORT HL7_Element *hl7_obx_units_id( HL7_Segment *segment );
/**
* Set the units_id (OBX.6.1.1) component.
*/
HL7_EXPORT int hl7_obx_set_units_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the units_id (OBX.6.1.1) component as a string.
*/
HL7_EXPORT int hl7_obx_set_units_id_str( HL7_Segment *segment, const char *value );
/**
* Get the units_text (OBX.6.1.2) component.
*/
HL7_EXPORT HL7_Element *hl7_obx_units_text( HL7_Segment *segment );
/**
* Set the units_text (OBX.6.1.2) component.
*/
HL7_EXPORT int hl7_obx_set_units_text( HL7_Segment *segment, HL7_Element *element );
/**
* Set the units_text (OBX.6.1.2) component as a string.
*/
HL7_EXPORT int hl7_obx_set_units_text_str( HL7_Segment *segment, const char *value );
/**
* Get the units_coding_system (OBX.6.1.3) component.
*/
HL7_EXPORT HL7_Element *hl7_obx_units_coding_system( HL7_Segment *segment );
/**
* Set the units_coding_system (OBX.6.1.3) component.
*/
HL7_EXPORT int hl7_obx_set_units_coding_system( HL7_Segment *segment, HL7_Element *element );
/**
* Set the units_coding_system (OBX.6.1.3) component as a string.
*/
HL7_EXPORT int hl7_obx_set_units_coding_system_str( HL7_Segment *segment, const char *value );
/**
* Get the reference_range (OBX.7) field.
*/
HL7_EXPORT HL7_Element *hl7_obx_reference_range( HL7_Segment *segment );
/**
* Set the reference_range (OBX.7) field.
*/
HL7_EXPORT int hl7_obx_set_reference_range( HL7_Segment *segment, HL7_Element *element );
/**
* Set the reference_range (OBX.7) field as a string.
*/
HL7_EXPORT int hl7_obx_set_reference_range_str( HL7_Segment *segment, const char *value );
/**
* Get the abnormal_flags_id (OBX.8.1) component.
*/
HL7_EXPORT HL7_Element *hl7_obx_abnormal_flags_id( HL7_Segment *segment );
/**
* Set the abnormal_flags_id (OBX.8.1) component.
*/
HL7_EXPORT int hl7_obx_set_abnormal_flags_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the abnormal_flags_id (OBX.8.1) component as a string.
*/
HL7_EXPORT int hl7_obx_set_abnormal_flags_id_str( HL7_Segment *segment, const char *value );
/**
* Get the probability (OBX.9) field.
*/
HL7_EXPORT HL7_Element *hl7_obx_probability( HL7_Segment *segment );
/**
* Set the probability (OBX.9) field.
*/
HL7_EXPORT int hl7_obx_set_probability( HL7_Segment *segment, HL7_Element *element );
/**
* Set the probability (OBX.9) field as a string.
*/
HL7_EXPORT int hl7_obx_set_probability_str( HL7_Segment *segment, const char *value );
/**
* Get the nature_of_abnormal_test_id (OBX.10.1) component.
*/
HL7_EXPORT HL7_Element *hl7_obx_nature_of_abnormal_test_id( HL7_Segment *segment );
/**
* Set the nature_of_abnormal_test_id (OBX.10.1) component.
*/
HL7_EXPORT int hl7_obx_set_nature_of_abnormal_test_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the nature_of_abnormal_test_id (OBX.10.1) component as a string.
*/
HL7_EXPORT int hl7_obx_set_nature_of_abnormal_test_id_str( HL7_Segment *segment, const char *value );
/**
* Get the observation_result_status (OBX.11.1) component.
*/
HL7_EXPORT HL7_Element *hl7_obx_observation_result_status( HL7_Segment *segment );
/**
* Set the observation_result_status (OBX.11.1) component.
*/
HL7_EXPORT int hl7_obx_set_observation_result_status( HL7_Segment *segment, HL7_Element *element );
/**
* Set the observation_result_status (OBX.11.1) component as a string.
*/
HL7_EXPORT int hl7_obx_set_observation_result_status_str( HL7_Segment *segment, const char *value );
/**
* Get the date_last_obs_normal_values (OBX.12) field.
*/
HL7_EXPORT time_t hl7_obx_date_last_obs_normal_values( HL7_Segment *segment );
/**
* Set the date_last_obs_normal_values (OBX.12) field.
*/
HL7_EXPORT int hl7_obx_set_date_last_obs_normal_values( HL7_Segment *segment, HL7_Element *element );
/**
* Set the date_last_obs_normal_values (OBX.12) field as a time_t.
*/
HL7_EXPORT int hl7_obx_set_date_last_obs_normal_values_time( HL7_Segment *segment, const time_t value );
/**
* Get the user_defined_access_checks (OBX.13) field.
*/
HL7_EXPORT HL7_Element *hl7_obx_user_defined_access_checks( HL7_Segment *segment );
/**
* Set the user_defined_access_checks (OBX.13) field.
*/
HL7_EXPORT int hl7_obx_set_user_defined_access_checks( HL7_Segment *segment, HL7_Element *element );
/**
* Set the user_defined_access_checks (OBX.13) field as a string.
*/
HL7_EXPORT int hl7_obx_set_user_defined_access_checks_str( HL7_Segment *segment, const char *value );
/**
* Get the date_time_of_observation (OBX.14) field.
*/
HL7_EXPORT time_t hl7_obx_date_time_of_observation( HL7_Segment *segment );
/**
* Set the date_time_of_observation (OBX.14) field.
*/
HL7_EXPORT int hl7_obx_set_date_time_of_observation( HL7_Segment *segment, HL7_Element *element );
/**
* Set the date_time_of_observation (OBX.14) field as a time_t.
*/
HL7_EXPORT int hl7_obx_set_date_time_of_observation_time( HL7_Segment *segment, const time_t value );
/**
* Get the producers_id (OBX.15.1) component.
*/
HL7_EXPORT HL7_Element *hl7_obx_producers_id( HL7_Segment *segment );
/**
* Set the producers_id (OBX.15.1) component.
*/
HL7_EXPORT int hl7_obx_set_producers_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the producers_id (OBX.15.1) component as a string.
*/
HL7_EXPORT int hl7_obx_set_producers_id_str( HL7_Segment *segment, const char *value );
/**
* Get the responsible_observer_id (OBX.16.1.1) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_obx_responsible_observer_id( HL7_Segment *segment );
/**
* Set the responsible_observer_id (OBX.16.1.1) subcomponent.
*/
HL7_EXPORT int hl7_obx_set_responsible_observer_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the responsible_observer_id (OBX.16.1.1) subcomponent as a string.
*/
HL7_EXPORT int hl7_obx_set_responsible_observer_id_str( HL7_Segment *segment, const char *value );
/**
* Get the responsible_observer_last_name (OBX.16.1.2) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_obx_responsible_observer_last_name( HL7_Segment *segment );
/**
* Set the responsible_observer_last_name (OBX.16.1.2) subcomponent.
*/
HL7_EXPORT int hl7_obx_set_responsible_observer_last_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the responsible_observer_last_name (OBX.16.1.2) subcomponent as a string.
*/
HL7_EXPORT int hl7_obx_set_responsible_observer_last_name_str( HL7_Segment *segment, const char *value );
/**
* Get the responsible_observer_first_name (OBX.16.1.3) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_obx_responsible_observer_first_name( HL7_Segment *segment );
/**
* Set the responsible_observer_first_name (OBX.16.1.3) subcomponent.
*/
HL7_EXPORT int hl7_obx_set_responsible_observer_first_name( HL7_Segment *segment, HL7_Element *element );
/**
* Set the responsible_observer_first_name (OBX.16.1.3) subcomponent as a string.
*/
HL7_EXPORT int hl7_obx_set_responsible_observer_first_name_str( HL7_Segment *segment, const char *value );
/**
* Get the responsible_observer_assigning_authority (OBX.16.1.11) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_obx_responsible_observer_assigning_authority( HL7_Segment *segment );
/**
* Set the responsible_observer_assigning_authority (OBX.16.1.11) subcomponent.
*/
HL7_EXPORT int hl7_obx_set_responsible_observer_assigning_authority( HL7_Segment *segment, HL7_Element *element );
/**
* Set the responsible_observer_assigning_authority (OBX.16.1.11) subcomponent as a string.
*/
HL7_EXPORT int hl7_obx_set_responsible_observer_assigning_authority_str( HL7_Segment *segment, const char *value );
/**
* Get the responsible_observer_assigning_facility (OBX.16.1.16) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_obx_responsible_observer_assigning_facility( HL7_Segment *segment );
/**
* Set the responsible_observer_assigning_facility (OBX.16.1.16) subcomponent.
*/
HL7_EXPORT int hl7_obx_set_responsible_observer_assigning_facility( HL7_Segment *segment, HL7_Element *element );
/**
* Set the responsible_observer_assigning_facility (OBX.16.1.16) subcomponent as a string.
*/
HL7_EXPORT int hl7_obx_set_responsible_observer_assigning_facility_str( HL7_Segment *segment, const char *value );
/**
* Get the observation_method_id (OBX.17.1.1) subcomponent.
*/
HL7_EXPORT HL7_Element *hl7_obx_observation_method_id( HL7_Segment *segment );
/**
* Set the observation_method_id (OBX.17.1.1) subcomponent.
*/
HL7_EXPORT int hl7_obx_set_observation_method_id( HL7_Segment *segment, HL7_Element *element );
/**
* Set the observation_method_id (OBX.17.1.1) subcomponent as a string.
*/
HL7_EXPORT int hl7_obx_set_observation_method_id_str( HL7_Segment *segment, const char *value );

END_C_DECL()

#endif /* HL7_SEG_OBX_H */
