/**
* \file seg_obx.c
*
* Observation segment (OBX) accessors for the HL7 parser.
*
* \internal
* Copyright (c) 2017 Juan Jose Comellas <juanjo@comellas.org>
*
* \warning DO NOT MODIFY THIS FILE.
*
* Autogenerated by the hl7segdef.py script on Tue Nov 14 11:09:38 2017
*/

/* ------------------------------------------------------------------------
   Headers
   ------------------------------------------------------------------------ */

#include <hl7parser/config.h>
#include <hl7parser/element.h>
#include <hl7parser/export.h>
#include <hl7parser/segment.h>
#include <hl7parser/seg_obx.h>

BEGIN_C_DECL()

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_id( HL7_Segment *segment )
{
    return hl7_element_int( hl7_segment_field( segment, 0 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_set_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_set_id_int( HL7_Segment *segment, const int value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_int( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_value_type( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 1, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_value_type( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 1, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_value_type_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 1, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_observation_identifier( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 2, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_identifier( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 2, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_identifier_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 2, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_observation_identifier_id( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 2, 0, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_identifier_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 2, 0, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_identifier_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 2, 0, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_observation_identifier_text( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 2, 0, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_identifier_text( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 2, 0, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_identifier_text_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 2, 0, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_observation_identifier_coding_system( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 2, 0, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_identifier_coding_system( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 2, 0, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_identifier_coding_system_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 2, 0, 2, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_observation_sub_id( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 3 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_sub_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 3, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_sub_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 3, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_observation_value_text( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 4 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_value_text( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 4, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_value_text_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 4, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_observation_value( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 4, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_value( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 4, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_value_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 4, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_units_id( HL7_Segment *segment )
{
    return hl7_segment_component_rep( segment, 5, 0, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_units_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component_rep( segment, 5, 0, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_units_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component_rep( segment, 5, 0, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_units_text( HL7_Segment *segment )
{
    return hl7_segment_component_rep( segment, 5, 0, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_units_text( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component_rep( segment, 5, 0, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_units_text_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component_rep( segment, 5, 0, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_units_coding_system( HL7_Segment *segment )
{
    return hl7_segment_component_rep( segment, 5, 0, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_units_coding_system( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component_rep( segment, 5, 0, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_units_coding_system_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component_rep( segment, 5, 0, 2, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_reference_range( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 6 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_reference_range( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 6, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_reference_range_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 6, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_abnormal_flags_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 7, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_abnormal_flags_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 7, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_abnormal_flags_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 7, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_probability( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 8 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_probability( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 8, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_probability_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 8, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_nature_of_abnormal_test_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 9, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_nature_of_abnormal_test_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 9, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_nature_of_abnormal_test_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 9, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_observation_result_status( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 10, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_result_status( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 10, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_result_status_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 10, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT time_t hl7_obx_date_last_obs_normal_values( HL7_Segment *segment )
{
    return hl7_element_date( hl7_segment_field( segment, 11 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_date_last_obs_normal_values( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 11, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_date_last_obs_normal_values_time( HL7_Segment *segment, const time_t value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_date( &element, value, true, true, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 11, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_user_defined_access_checks( HL7_Segment *segment )
{
    return hl7_segment_field( segment, 12 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_user_defined_access_checks( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 12, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_user_defined_access_checks_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 12, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT time_t hl7_obx_date_time_of_observation( HL7_Segment *segment )
{
    return hl7_element_date( hl7_segment_field( segment, 13 ) );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_date_time_of_observation( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_field( segment, 13, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_date_time_of_observation_time( HL7_Segment *segment, const time_t value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_set_date( &element, value, true, true, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_field( segment, 13, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_producers_id( HL7_Segment *segment )
{
    return hl7_segment_component( segment, 14, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_producers_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_component( segment, 14, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_producers_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_component( segment, 14, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_responsible_observer_id( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 15, 0, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_responsible_observer_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 15, 0, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_responsible_observer_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 15, 0, 0, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_responsible_observer_last_name( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 15, 0, 1 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_responsible_observer_last_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 15, 0, 1, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_responsible_observer_last_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 15, 0, 1, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_responsible_observer_first_name( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 15, 0, 2 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_responsible_observer_first_name( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 15, 0, 2, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_responsible_observer_first_name_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 15, 0, 2, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_responsible_observer_assigning_authority( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 15, 0, 10 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_responsible_observer_assigning_authority( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 15, 0, 10, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_responsible_observer_assigning_authority_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 15, 0, 10, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_responsible_observer_assigning_facility( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 15, 0, 15 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_responsible_observer_assigning_facility( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 15, 0, 15, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_responsible_observer_assigning_facility_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 15, 0, 15, &element ) : rc );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT HL7_Element *hl7_obx_observation_method_id( HL7_Segment *segment )
{
    return hl7_segment_subcomponent( segment, 16, 0, 0 );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_method_id( HL7_Segment *segment, HL7_Element *element )
{
    return hl7_segment_set_subcomponent( segment, 16, 0, 0, element );
}

/* ------------------------------------------------------------------------ */
HL7_EXPORT int hl7_obx_set_observation_method_id_str( HL7_Segment *segment, const char *value )
{
    int         rc;
    HL7_Element element;

    rc = hl7_element_copy_str( &element, value, segment->allocator );

    return ( rc == 0 ? hl7_segment_set_subcomponent( segment, 16, 0, 0, &element ) : rc );
}

END_C_DECL()
